### ISSUE TITLE
The link to the D lab Machine Learning Working group is broken

### ISSUE THREAD

**Issue by Leenabh** [dlab-berkeley/Python-Deep-Learning-Legacy#9]
The first under resources in READ.me which points to the following shows "Page not found"

https://dlab.berkeley.edu/working-groups/machine-learning-working-group-0

**Comment by aculich** [comment]
Thanks @Leenabh ! The working group is no longer active and while the page exists still on an old archived version of our website, I think it should be removed from the README.md here.

**Comment by seanmperez** [comment]
Will fix, thanks @Leenabh and @aculich!
